version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: hitchr-jekyll
    ports:
      - "4000:4000"
      - "35729:35729"  # For live reload
    volumes:
      - .:/srv/jekyll
      - jekyll_cache:/srv/jekyll/.jekyll-cache
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "bundle install &&
               jekyll serve --host 0.0.0.0 --livereload --force_polling"

volumes:
  jekyll_cache:
  bundle_cache: